package main_test

import (
	"database/sql"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	_ "modernc.org/sqlite"
)

// seedFixtureDB writes a golden schema fixture (schema_vN.sql under
// internal/db/testdata, regenerated by gen_fixtures.sh) to a new file DB at
// dbPath. This package cannot import internal/db test helpers, so the path is
// relative to this package's CWD (standard Go convention).
func seedFixtureDB(t *testing.T, dbPath, fixture string) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "internal", "db", "testdata", fixture))
	if err != nil {
		t.Fatalf("read fixture %s: %v", fixture, err)
	}
	conn, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open seed db: %v", err)
	}
	defer conn.Close()
	if _, err := conn.Exec(string(raw)); err != nil {
		t.Fatalf("seed fixture %s: %v", fixture, err)
	}
}

// seedPreV1DB writes a pre-scrub (v0) database at dbPath with rows that
// contain secrets in title/what/learned. The returned cleanup closes the
// seeding connection so the binary can open the file afresh.
func seedPreV1DB(t *testing.T, dbPath string) {
	t.Helper()
	seedFixtureDB(t, dbPath, "schema_v0.sql")
	conn, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open seed db: %v", err)
	}
	defer conn.Close()
	rows := []struct {
		id, taskType, kind, title, what, learned, tags string
	}{
		{
			id: "mem_legacy_secret", taskType: "crm_upload", kind: "error_resolution",
			title: "Upload failed for user", what: "host 10.0.0.5 returned 500 for alice@example.com payload",
			learned: "retry uploads against alice@example.com after 30 seconds", tags: "hubspot retry",
		},
		{
			id: "mem_legacy_clean", taskType: "crm_upload", kind: "task_pattern",
			title: "Use bulk endpoint", what: "batch endpoint accepts up to 100 rows",
			learned: "send all rows in a single POST", tags: "hubspot bulk",
		},
	}
	for i, r := range rows {
		ts := int64(1700000000 + i)
		_, err := conn.Exec(`
			INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
			VALUES (?, 'sess_legacy', ?, ?, ?, ?, ?, ?, ?, ?, ?)
		`, r.id, r.taskType, r.kind, r.title, r.what, r.learned, r.tags, "legacy_fp_"+r.id, ts, ts)
		if err != nil {
			t.Fatalf("seed row %s: %v", r.id, err)
		}
	}
}

func runBinary(t *testing.T, dbPath string, args ...string) (stdout, stderr string, exitCode int) {
	t.Helper()
	cmd := exec.Command(binaryPath, args...)
	cmd.Env = append(os.Environ(), "DROIDS_MEM_DB="+dbPath)
	var outBuf, errBuf strings.Builder
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf
	err := cmd.Run()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return outBuf.String(), errBuf.String(), ee.ExitCode()
		}
		t.Fatalf("run %v: %v", args, err)
	}
	return outBuf.String(), errBuf.String(), 0
}

func openMigratedDB(t *testing.T, dbPath string) *sql.DB {
	t.Helper()
	conn, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open migrated db: %v", err)
	}
	t.Cleanup(func() { conn.Close() })
	return conn
}

// TestE2E_MigrateRescrub covers the full upgrade path:
//  1. Pre-v1.0 DB seeded with rows containing secrets.
//  2. Binary boot fails (no scrub baseline).
//  3. `migrate --rescrub` rewrites rows and sets the sentinel (the porter
//     tokenizer flip already landed at open via the boot ladder rung 7→8).
//  4. Subsequent boot succeeds; raw secrets are gone, bracket tokens present.
func TestE2E_MigrateRescrub(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "mem.db")
	seedPreV1DB(t, dbPath)

	// migrate bypasses the boot gate, so it is exercised directly on the
	// pre-v1 DB here. (A normal command would auto-run this same rescrub via
	// the gate — see TestE2E_BootGateAutoRescrub — but that would leave nothing
	// for the explicit migrate to redact, so we don't trigger it first.)
	stdout, _, code := runBinary(t, dbPath, "migrate", "--rescrub")
	if code != 0 {
		t.Fatalf("migrate --rescrub failed (exit %d): %s", code, stdout)
	}
	var summary struct {
		Mode               string `json:"mode"`
		RowsScanned        int    `json:"rows_scanned"`
		RowsRewritten      int    `json:"rows_rewritten"`
		RowsWithRedactions int    `json:"rows_with_redactions"`
		TotalRedactions    int    `json:"total_redactions"`
		BaselineSet        bool   `json:"scrub_baseline_complete_set"`
		PatternVersion     int    `json:"pattern_version"`
	}
	if err := json.Unmarshal([]byte(stdout), &summary); err != nil {
		t.Fatalf("parse migrate summary: %v\nraw: %s", err, stdout)
	}
	if summary.Mode != "rescrub" {
		t.Errorf("mode = %q, want 'rescrub'", summary.Mode)
	}
	if summary.RowsScanned != 2 {
		t.Errorf("rows_scanned = %d, want 2", summary.RowsScanned)
	}
	// rows_rewritten counts rows whose content actually changed after scrub
	// (SM-R4): only the legacy_secret row changed, so 1 — not 2.
	if summary.RowsRewritten != 1 {
		t.Errorf("rows_rewritten = %d, want 1 (only legacy_secret row changed)", summary.RowsRewritten)
	}
	if summary.RowsWithRedactions != 1 {
		t.Errorf("rows_with_redactions = %d, want 1 (only legacy_secret row had secrets)", summary.RowsWithRedactions)
	}
	if summary.TotalRedactions < 2 {
		t.Errorf("total_redactions = %d, want >=2 (1 IP + 2 emails)", summary.TotalRedactions)
	}
	if !summary.BaselineSet {
		t.Error("scrub_baseline_complete_set = false, want true")
	}

	// Boot gate now passes — verify by running a normal subcommand.
	_, stderr, code := runBinary(t, dbPath, "list")
	if code != 0 {
		t.Fatalf("post-migrate boot failed (exit %d): %s", code, stderr)
	}

	// Direct SQL verification: secrets gone, brackets present.
	conn := openMigratedDB(t, dbPath)
	var what, learned string
	if err := conn.QueryRow(
		`SELECT what, learned FROM memories WHERE id = 'mem_legacy_secret'`,
	).Scan(&what, &learned); err != nil {
		t.Fatalf("read migrated row: %v", err)
	}
	for _, raw := range []string{"alice@example.com", "10.0.0.5"} {
		if strings.Contains(what, raw) || strings.Contains(learned, raw) {
			t.Errorf("raw secret %q still present after rescrub", raw)
		}
	}
	if !strings.Contains(what, "[PRIVATE_IP]") {
		t.Errorf("expected [PRIVATE_IP] in what, got %q", what)
	}
	if !strings.Contains(what, "[EMAIL]") || !strings.Contains(learned, "[EMAIL]") {
		t.Errorf("expected [EMAIL] in what+learned, got what=%q learned=%q", what, learned)
	}

	// scrub_counts populated for the dirty row, NULL for the clean one.
	var dirtyCounts sql.NullString
	if err := conn.QueryRow(
		`SELECT scrub_counts FROM memories WHERE id = 'mem_legacy_secret'`,
	).Scan(&dirtyCounts); err != nil {
		t.Fatalf("read scrub_counts: %v", err)
	}
	if !dirtyCounts.Valid {
		t.Error("expected scrub_counts populated for legacy_secret row")
	}

	var cleanCounts sql.NullString
	if err := conn.QueryRow(
		`SELECT scrub_counts FROM memories WHERE id = 'mem_legacy_clean'`,
	).Scan(&cleanCounts); err != nil {
		t.Fatalf("read clean scrub_counts: %v", err)
	}
	if cleanCounts.Valid {
		t.Errorf("expected NULL scrub_counts for clean row, got %q", cleanCounts.String)
	}

	// Sentinel persisted.
	var sentinel string
	if err := conn.QueryRow(
		`SELECT value FROM meta WHERE key = 'scrub_baseline_complete'`,
	).Scan(&sentinel); err != nil {
		t.Fatalf("read sentinel: %v", err)
	}
	if sentinel != "1" {
		t.Errorf("sentinel = %q, want '1'", sentinel)
	}

	// Tokenizer flip landed via the boot ladder rung 7→8 (not migrate):
	// the stored CREATE VIRTUAL TABLE text carries the porter stemmer.
	var ftsSQL string
	if err := conn.QueryRow(
		`SELECT sql FROM sqlite_master WHERE type='table' AND name='memories_fts'`,
	).Scan(&ftsSQL); err != nil {
		t.Fatalf("read memories_fts sql: %v", err)
	}
	if !strings.Contains(ftsSQL, "tokenize='porter unicode61 tokenchars ''_-'''") {
		t.Errorf("memories_fts not porter after upgrade:\n%s", ftsSQL)
	}

	// FTS retokenized — `field-mapping`-style atomic tokens should be searchable.
	// Insert a fresh row through the binary and verify the new tokenizer indexes it.
	_, _, code = runBinary(t, dbPath, "save",
		"--task-type", "crm_upload",
		"--kind", "task_pattern",
		"--title", "field-mapping refresh",
		"--what", "phone_number maps to phone",
		"--learned", "rerun the mapping job after schema bumps",
		"--session-id", "sess_post_migrate",
	)
	if code != 0 {
		t.Fatalf("post-migrate save failed (exit %d)", code)
	}
}

// TestE2E_MigrateNoRescrub confirms the lighter path: baseline is set but row
// bodies are NOT rewritten (plaintext stays). The tokenizer flip is the boot
// ladder's job, not migrate's.
func TestE2E_MigrateNoRescrub(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "mem.db")
	seedPreV1DB(t, dbPath)

	stdout, _, code := runBinary(t, dbPath, "migrate", "--no-rescrub")
	if code != 0 {
		t.Fatalf("migrate --no-rescrub failed (exit %d): %s", code, stdout)
	}
	var summary struct {
		Mode               string `json:"mode"`
		RowsScanned        int    `json:"rows_scanned"`
		RowsRewritten      int    `json:"rows_rewritten"`
		RowsWithRedactions int    `json:"rows_with_redactions"`
		BaselineSet        bool   `json:"scrub_baseline_complete_set"`
	}
	if err := json.Unmarshal([]byte(stdout), &summary); err != nil {
		t.Fatalf("parse migrate summary: %v\nraw: %s", err, stdout)
	}
	if summary.Mode != "no-rescrub" {
		t.Errorf("mode = %q, want 'no-rescrub'", summary.Mode)
	}
	if summary.RowsRewritten != 0 {
		t.Errorf("rows_rewritten = %d, want 0 on no-rescrub", summary.RowsRewritten)
	}
	if !summary.BaselineSet {
		t.Error("expected baseline set")
	}

	conn := openMigratedDB(t, dbPath)
	var what string
	if err := conn.QueryRow(
		`SELECT what FROM memories WHERE id = 'mem_legacy_secret'`,
	).Scan(&what); err != nil {
		t.Fatalf("read legacy row: %v", err)
	}
	if !strings.Contains(what, "alice@example.com") {
		t.Error("no-rescrub should NOT touch row bodies; expected raw email to remain")
	}

	// Boot now succeeds even though plaintext remains.
	_, stderr, code := runBinary(t, dbPath, "list")
	if code != 0 {
		t.Fatalf("post --no-rescrub boot failed (exit %d): %s", code, stderr)
	}
}

// TestE2E_BootGateAutoRescrub covers issue #29: a normal command against a
// stale (pre-baseline) DB must not die on the boot gate. The gate auto-runs
// `migrate --rescrub`, logs a loud line, and lets the command proceed — so the
// memory tools never go dark waiting on a manual migration.
func TestE2E_BootGateAutoRescrub(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "mem.db")
	seedPreV1DB(t, dbPath)

	// A gated command now succeeds instead of exiting non-zero.
	_, stderr, code := runBinary(t, dbPath, "list")
	if code != 0 {
		t.Fatalf("expected auto-remediated boot to succeed, got exit %d: %s", code, stderr)
	}
	if !strings.Contains(stderr, "auto-rescrubbed") {
		t.Errorf("expected loud auto-migration log on stderr, got: %q", stderr)
	}

	// Secrets in the seeded row were scrubbed by the auto-migration.
	conn := openMigratedDB(t, dbPath)
	var what, learned string
	if err := conn.QueryRow(
		`SELECT what, learned FROM memories WHERE id = 'mem_legacy_secret'`,
	).Scan(&what, &learned); err != nil {
		t.Fatalf("read migrated row: %v", err)
	}
	for _, raw := range []string{"alice@example.com", "10.0.0.5"} {
		if strings.Contains(what, raw) || strings.Contains(learned, raw) {
			t.Errorf("raw secret %q still present after auto-rescrub", raw)
		}
	}

	// Baseline sentinel is set, so a second command does NOT re-trigger.
	_, stderr2, code := runBinary(t, dbPath, "list")
	if code != 0 {
		t.Fatalf("second boot failed (exit %d): %s", code, stderr2)
	}
	if strings.Contains(stderr2, "rescrub") {
		t.Errorf("auto-migration re-fired on an already-migrated DB: %q", stderr2)
	}
}

// TestE2E_MigrateRejectsAmbiguousFlags confirms the CLI guard between
// --rescrub and --no-rescrub.
func TestE2E_MigrateRejectsAmbiguousFlags(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "mem.db")
	seedPreV1DB(t, dbPath)

	_, _, code := runBinary(t, dbPath, "migrate", "--rescrub", "--no-rescrub")
	if code == 0 {
		t.Error("expected non-zero exit when both flags supplied")
	}

	_, _, code = runBinary(t, dbPath, "migrate")
	if code == 0 {
		t.Error("expected non-zero exit when neither flag supplied")
	}
}

// TestE2E_MigrateCollisionFailLoud proves SM-R5 through the binary: two rows
// whose POST-scrub fingerprints collide must abort `migrate --rescrub` with
// exit 5 (conflict class), an error naming the offending row + fingerprint,
// no partial rewrite, and no sentinel — the operator resolves the duplicate.
func TestE2E_MigrateCollisionFailLoud(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "mem.db")
	seedFixtureDB(t, dbPath, "schema_v0.sql")

	conn, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open seed db: %v", err)
	}
	now := int64(1700000000)
	// Distinct pre-scrub titles that scrub to the same token stream
	// (alice@/bob@example.com → [EMAIL]) → same post-scrub fingerprint.
	seed := []struct{ id, title string }{
		{id: "mem_coll_a", title: "retry alice@example.com"},
		{id: "mem_coll_b", title: "retry bob@example.com"},
	}
	for _, r := range seed {
		if _, err := conn.Exec(`
			INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
			VALUES (?, 'sess', 'crm_upload', 'error_resolution', ?, 'row ' || ?, 'handle it the same way', '', 'fp_' || ?, ?, ?)`,
			r.id, r.title, r.id, r.id, now, now); err != nil {
			conn.Close()
			t.Fatalf("seed %s: %v", r.id, err)
		}
	}
	conn.Close()

	_, stderr, code := runBinary(t, dbPath, "migrate", "--rescrub")
	if code != 5 {
		t.Fatalf("migrate --rescrub on colliding rows: exit = %d, want 5 (conflict); stderr: %s", code, stderr)
	}
	var env struct {
		Code       string `json:"code"`
		Message    string `json:"message"`
		Retryable  bool   `json:"retryable"`
		Suggestion string `json:"suggestion"`
	}
	if err := json.Unmarshal([]byte(stderr), &env); err != nil {
		t.Fatalf("parse error envelope: %v\nraw: %s", err, stderr)
	}
	if env.Code != "migrate_collision" {
		t.Errorf("error code = %q, want 'migrate_collision'", env.Code)
	}
	if !strings.Contains(env.Message, "mem_coll_b") || !strings.Contains(env.Message, "mem_coll_a") {
		t.Errorf("error must name the offending row and collision partner, got: %q", env.Message)
	}
	if env.Retryable {
		t.Error("collision must not be flagged retryable — the operator decides")
	}

	conn = openMigratedDB(t, dbPath)
	// No partial rewrite: the raw email survives in the aborted row.
	var title string
	if err := conn.QueryRow(`SELECT title FROM memories WHERE id = 'mem_coll_b'`).Scan(&title); err != nil {
		t.Fatalf("read mem_coll_b: %v", err)
	}
	if !strings.Contains(title, "bob@example.com") {
		t.Errorf("row body rewritten despite abort: %q", title)
	}
	// No sentinel: the boot gate stays closed, so a normal command must fail.
	var n int
	if err := conn.QueryRow(`SELECT COUNT(*) FROM meta`).Scan(&n); err != nil {
		t.Fatalf("count meta: %v", err)
	}
	if n != 0 {
		t.Errorf("meta has %d rows after aborted migrate; want 0 (no sentinel)", n)
	}
	_, _, code = runBinary(t, dbPath, "list")
	if code == 0 {
		t.Error("boot gate should still be closed after aborted migrate (sentinel absent)")
	}
}
