package db_test

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/samuelmolero26/droids-mem/internal/db"
	_ "modernc.org/sqlite"
)

// loadFixture opens an in-memory DB and replays a golden per-version schema
// fixture from testdata/ (schema_v0.sql … schema_v7.sql, regenerated by
// testdata/gen_fixtures.sh). Each fixture terminates with
// `PRAGMA user_version = N;`, so db.Migrate starts at exactly rung N.
func loadFixture(t *testing.T, name string) *sql.DB {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	conn, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("open in-memory db: %v", err)
	}
	if _, err := conn.Exec(string(raw)); err != nil {
		conn.Close()
		t.Fatalf("seed fixture %s: %v", name, err)
	}
	t.Cleanup(func() { conn.Close() })
	return conn
}

func userVersion(t *testing.T, conn *sql.DB) int {
	t.Helper()
	var v int
	if err := conn.QueryRow("PRAGMA user_version").Scan(&v); err != nil {
		t.Fatalf("read user_version: %v", err)
	}
	return v
}

func tableColumns(t *testing.T, conn *sql.DB, table string) []string {
	t.Helper()
	rows, err := conn.Query("SELECT name FROM pragma_table_info(?) ORDER BY cid", table)
	if err != nil {
		t.Fatalf("pragma_table_info(%s): %v", table, err)
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatalf("scan column: %v", err)
		}
		cols = append(cols, name)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("pragma_table_info rows: %v", err)
	}
	return cols
}

func tableExists(t *testing.T, conn *sql.DB, name string) bool {
	t.Helper()
	var count int
	if err := conn.QueryRow(
		`SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?`, name,
	).Scan(&count); err != nil {
		t.Fatalf("inspect for %s: %v", name, err)
	}
	return count == 1
}

// indexDefs returns "name(col,col DESC,…)" per index. indexNames compares only
// names, which a DROP+CREATE that keeps the name but changes the columns slips
// straight past — the exact drift that would leave a migrated DB and a fresh DB
// on different schemas at the same user_version. Compares pragma_index_xinfo
// rather than sqlite_master.sql because the raw DDL text differs by whitespace
// and IF NOT EXISTS between the schema and migration paths.
func indexDefs(t *testing.T, conn *sql.DB) []string {
	t.Helper()
	rows, err := conn.Query(`
		SELECT m.name, (
			SELECT group_concat(x.name || CASE WHEN x.desc THEN ' DESC' ELSE '' END)
			FROM pragma_index_xinfo(m.name) x WHERE x.key = 1
		)
		FROM sqlite_master m
		WHERE m.type = 'index' AND m.name NOT LIKE 'sqlite_%'`)
	if err != nil {
		t.Fatalf("inspect index defs: %v", err)
	}
	defer rows.Close()
	var defs []string
	for rows.Next() {
		var name string
		var cols sql.NullString
		if err := rows.Scan(&name, &cols); err != nil {
			t.Fatalf("scan index def: %v", err)
		}
		defs = append(defs, name+"("+cols.String+")")
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("index def rows: %v", err)
	}
	sort.Strings(defs)
	return defs
}

func indexNames(t *testing.T, conn *sql.DB) []string {
	t.Helper()
	rows, err := conn.Query(
		`SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%'`,
	)
	if err != nil {
		t.Fatalf("inspect indexes: %v", err)
	}
	defer rows.Close()
	var names []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			t.Fatalf("scan index: %v", err)
		}
		names = append(names, n)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("index rows: %v", err)
	}
	sort.Strings(names)
	return names
}

func TestInit_FreshDBStampsUserVersion(t *testing.T) {
	conn := newTestDB(t)
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("fresh DB user_version = %d, want %d", got, want)
	}
}

func TestInit_FreshDBHasScrubColumns(t *testing.T) {
	conn := newTestDB(t)
	cols := tableColumns(t, conn, "memories")
	wantCols := map[string]bool{
		"scope":                 false,
		"scrub_pattern_version": false,
		"scrub_counts":          false,
	}
	for _, c := range cols {
		if _, ok := wantCols[c]; ok {
			wantCols[c] = true
		}
	}
	for name, found := range wantCols {
		if !found {
			t.Errorf("fresh DB missing memories.%s", name)
		}
	}
}

func TestInit_FreshDBHasMetaTable(t *testing.T) {
	conn := newTestDB(t)
	if !tableExists(t, conn, "meta") {
		t.Fatal("fresh DB missing meta table")
	}
}

// triggerSQL returns the stored CREATE statement for a trigger.
func triggerSQL(t *testing.T, conn *sql.DB, name string) string {
	t.Helper()
	var sqlText string
	if err := conn.QueryRow(
		`SELECT sql FROM sqlite_master WHERE type='trigger' AND name=?`, name,
	).Scan(&sqlText); err != nil {
		t.Fatalf("read trigger %s sql: %v", name, err)
	}
	return sqlText
}

func hasExpandColumns(cols []string) (hasCount, hasLast bool) {
	for _, c := range cols {
		switch c {
		case "expand_count":
			hasCount = true
		case "last_expanded_at":
			hasLast = true
		}
	}
	return
}

func TestInit_FreshDBHasExpandColumns(t *testing.T) {
	conn := newTestDB(t)
	hasCount, hasLast := hasExpandColumns(tableColumns(t, conn, "memories"))
	if !hasCount {
		t.Error("fresh DB missing memories.expand_count")
	}
	if !hasLast {
		t.Error("fresh DB missing memories.last_expanded_at")
	}
}

// The memories_au trigger must be scoped to the indexed text columns so a
// metadata-only update (the Expand signal increment) does not re-index FTS.
func TestInit_FreshDBScopesUpdateTrigger(t *testing.T) {
	conn := newTestDB(t)
	if sqlText := triggerSQL(t, conn, "memories_au"); !strings.Contains(sqlText, "UPDATE OF") {
		t.Errorf("memories_au not scoped to text columns:\n%s", sqlText)
	}
}

func TestMigrate_V1toV2AddsExpandColumns(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	hasCount, hasLast := hasExpandColumns(tableColumns(t, conn, "memories"))
	if !hasCount {
		t.Error("migrated DB missing memories.expand_count")
	}
	if !hasLast {
		t.Error("migrated DB missing memories.last_expanded_at")
	}
	// Migrate runs the full ladder, so the version lands on the current head.
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
}

// A v0 DB carries the original unscoped memories_au trigger; the v1→v2 rung
// must replace it with the scoped form.
func TestMigrate_V1toV2ScopesUpdateTrigger(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	if sqlText := triggerSQL(t, conn, "memories_au"); strings.Contains(sqlText, "UPDATE OF") {
		t.Fatalf("pre-migrate trigger already scoped — fixture wrong:\n%s", sqlText)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if sqlText := triggerSQL(t, conn, "memories_au"); !strings.Contains(sqlText, "UPDATE OF") {
		t.Errorf("migrated memories_au not scoped:\n%s", sqlText)
	}
}

// The scoped trigger keeps the Expand signal write off the FTS index: bumping
// expand_count must not error and must leave the row findable unchanged.
func TestMigrate_ExpandIncrementDoesNotTouchFTS(t *testing.T) {
	conn := newTestDB(t)
	insertMemory(t, conn, "mem_01", "phone field mapping", "field was wrong", "use phone not phone_number", "hubspot phone")

	if _, err := conn.Exec(`UPDATE memories SET expand_count = expand_count + 1, last_expanded_at = 123 WHERE id = 'mem_01'`); err != nil {
		t.Fatalf("expand increment: %v", err)
	}

	var count int
	var last sql.NullInt64
	if err := conn.QueryRow(`SELECT expand_count, last_expanded_at FROM memories WHERE id = 'mem_01'`).Scan(&count, &last); err != nil {
		t.Fatalf("read expand cols: %v", err)
	}
	if count != 1 || !last.Valid || last.Int64 != 123 {
		t.Errorf("expand columns = (%d, %v), want (1, 123)", count, last)
	}

	var title string
	if err := conn.QueryRow(`
		SELECT m.title FROM memories_fts fts
		JOIN memories m ON m.rowid = fts.rowid
		WHERE memories_fts MATCH 'phone' ORDER BY fts.rank LIMIT 1
	`).Scan(&title); err != nil {
		t.Errorf("FTS search after expand increment: %v", err)
	}
	if title != "phone field mapping" {
		t.Errorf("unexpected title after expand increment: %q", title)
	}
}

func TestMigrate_V0toV1(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	if got := userVersion(t, conn); got != 0 {
		t.Fatalf("seed user_version = %d, want 0", got)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
	cols := tableColumns(t, conn, "memories")
	wantCols := []string{"scope", "scrub_pattern_version", "scrub_counts"}
	for _, want := range wantCols {
		if !slices.Contains(cols, want) {
			t.Errorf("migrated DB missing memories.%s", want)
		}
	}
	if !tableExists(t, conn, "meta") {
		t.Error("migrated DB missing meta table")
	}
}

func TestMigrate_PreservesRows(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	now := int64(1000000)
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
		VALUES ('mem_legacy', 'sess_legacy', 'crm', 'task_pattern', 't', 'w', 'l', '', 'fp_legacy', ?, ?)`,
		now, now); err != nil {
		t.Fatalf("seed row: %v", err)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	var scope string
	var version int
	var scrubCounts sql.NullString
	if err := conn.QueryRow(
		`SELECT scope, scrub_pattern_version, scrub_counts FROM memories WHERE id = 'mem_legacy'`,
	).Scan(&scope, &version, &scrubCounts); err != nil {
		t.Fatalf("read migrated row: %v", err)
	}
	// The v4→v5 backfill (ADR-0028) reinterprets every pre-v5 row as personal,
	// so a fully-migrated legacy row lands on 'personal' regardless of the
	// v0→v1 column default it first received.
	if scope != "personal" {
		t.Errorf("migrated scope = %q, want 'personal' (ADR-0028 backfill)", scope)
	}
	if version != 1 {
		t.Errorf("scrub_pattern_version default = %d, want 1", version)
	}
	if scrubCounts.Valid {
		t.Errorf("scrub_counts default = %q, want NULL", scrubCounts.String)
	}
}

func TestMigrate_Idempotent(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("first Migrate: %v", err)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("second Migrate: %v", err)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("user_version = %d, want %d", got, want)
	}
}

func TestInit_IdempotentOnExistingDB(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	if err := db.Init(conn); err != nil {
		t.Fatalf("first Init: %v", err)
	}
	if err := db.Init(conn); err != nil {
		t.Fatalf("second Init: %v", err)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("user_version = %d, want %d", got, want)
	}
}

// normalizeSchemaSQL folds fresh multi-line DDL and the canonical
// ALTER-appended tails onto one whitespace-normalized form. sqlite already
// strips IF NOT EXISTS and trailing semicolons from stored text; single
// spaces inside string literals (e.g. the FTS tokenizer) are preserved by
// Fields/Join.
func normalizeSchemaSQL(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// schemaSQLSnapshot keyed (type,name) → normalized stored sql for every user
// schema object, excluding the FTS5 shadow tables (memories_fts_data/_idx/
// _content/_docsize/_config) and sqlite_autoindex rows per SM-R6. The FTS
// virtual table itself IS included — its CREATE text carries the tokenizer,
// asserted separately by the callers.
func schemaSQLSnapshot(t *testing.T, conn *sql.DB) map[[2]string]string {
	t.Helper()
	rows, err := conn.Query(`
		SELECT type, name, sql FROM sqlite_master
		WHERE sql IS NOT NULL
		  AND name NOT LIKE 'memories_fts_%'
		  AND name NOT LIKE 'sqlite_autoindex%'
	`)
	if err != nil {
		t.Fatalf("snapshot sqlite_master: %v", err)
	}
	defer rows.Close()
	out := make(map[[2]string]string)
	for rows.Next() {
		var typ, name, sqlText string
		if err := rows.Scan(&typ, &name, &sqlText); err != nil {
			t.Fatalf("scan sqlite_master row: %v", err)
		}
		out[[2]string{typ, name}] = normalizeSchemaSQL(sqlText)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("sqlite_master rows: %v", err)
	}
	return out
}

// ftsTableSQL returns the stored CREATE VIRTUAL TABLE text for memories_fts.
func ftsTableSQL(t *testing.T, conn *sql.DB) string {
	t.Helper()
	var sqlText string
	if err := conn.QueryRow(
		`SELECT sql FROM sqlite_master WHERE type='table' AND name='memories_fts'`,
	).Scan(&sqlText); err != nil {
		t.Fatalf("read memories_fts sql: %v", err)
	}
	return sqlText
}

// TestInit_FreshMatchesMigratedShape proves SM-R6: every historical path
// vN→current (N = 0..7) converges to a schema byte-identical to fresh for all
// user objects, after whitespace normalization. It is also the ONLY guard
// against gen_fixtures.sh's inline rung SQL drifting from the Go consts — if
// the script's copy diverges, the checked-in fixture fails convergence here.
func TestInit_FreshMatchesMigratedShape(t *testing.T) {
	const porterTokenizer = "tokenize='porter unicode61 tokenchars ''_-'''"
	for _, v := range []int{0, 1, 2, 3, 4, 5, 6, 7} {
		t.Run(fmt.Sprintf("v%d", v), func(t *testing.T) {
			fresh := newTestDB(t)
			migrated := loadFixture(t, fmt.Sprintf("schema_v%d.sql", v))
			if err := db.Migrate(migrated); err != nil {
				t.Fatalf("Migrate: %v", err)
			}
			if got, want := userVersion(t, migrated), db.CurrentSchemaVersion; got != want {
				t.Errorf("post-migrate user_version = %d, want %d", got, want)
			}

			wantSnap := schemaSQLSnapshot(t, fresh)
			gotSnap := schemaSQLSnapshot(t, migrated)
			for key, wantSQL := range wantSnap {
				if gotSQL, ok := gotSnap[key]; !ok {
					t.Errorf("migrated DB missing object %v", key)
				} else if gotSQL != wantSQL {
					t.Errorf("object %v diverges:\n fresh   = %s\n migrate = %s", key, wantSQL, gotSQL)
				}
			}
			for key := range gotSnap {
				if _, ok := wantSnap[key]; !ok {
					t.Errorf("migrated DB has extra object %v not in fresh", key)
				}
			}

			// The tokenizer flip is asserted from the stored CREATE VIRTUAL
			// TABLE text, not from row counts (SM-R6).
			if fts := ftsTableSQL(t, migrated); !strings.Contains(fts, porterTokenizer) {
				t.Errorf("migrated memories_fts missing porter tokenizer:\n%s", fts)
			}
			if fts := ftsTableSQL(t, fresh); !strings.Contains(fts, porterTokenizer) {
				t.Errorf("fresh memories_fts missing porter tokenizer:\n%s", fts)
			}
		})
	}
}

// TestMigrate_V7toV8FlipsFTS proves SM-R1 on the real v7 shape: seeding the
// v7 fixture (trigram FTS + 4-column recency indexes) and running the ladder
// must land on CurrentSchemaVersion with the porter tokenizer, a row-preserving
// FTS reindex, and a no-op second Migrate. Porter stemming is proven
// behaviorally: a query for "cancellation" matches a row containing "cancel".
func TestMigrate_V7toV8FlipsFTS(t *testing.T) {
	conn := loadFixture(t, "schema_v7.sql")
	if fts := ftsTableSQL(t, conn); strings.Contains(fts, "porter") {
		t.Fatalf("v7 fixture already porter — wrong fixture shape:\n%s", fts)
	}

	now := int64(1000000)
	for _, m := range []struct {
		id, title, what, learned string
	}{
		{id: "mem_a", title: "cancel the sync job", what: "retry the sync", learned: "cancellation handling is manual"},
		{id: "mem_b", title: "port mapping", what: "host moved", learned: "check the port table first"},
	} {
		if _, err := conn.Exec(`
			INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
			VALUES (?, 'sess', 'crm', 'task_pattern', ?, ?, ?, '', ?, ?, ?)`,
			m.id, m.title, m.what, m.learned, "fp_"+m.id, now, now); err != nil {
			t.Fatalf("seed row %s: %v", m.id, err)
		}
	}

	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Fatalf("post-migrate user_version = %d, want %d", got, want)
	}
	if fts := ftsTableSQL(t, conn); !strings.Contains(fts, "tokenize='porter unicode61 tokenchars ''_-'''") {
		t.Errorf("memories_fts not porter after v7→v8:\n%s", fts)
	}

	// Row-preserving: the rung reindexes every memories row into memories_fts.
	var ftsCount, memCount int
	if err := conn.QueryRow(`SELECT COUNT(*) FROM memories_fts`).Scan(&ftsCount); err != nil {
		t.Fatalf("count memories_fts: %v", err)
	}
	if err := conn.QueryRow(`SELECT COUNT(*) FROM memories`).Scan(&memCount); err != nil {
		t.Fatalf("count memories: %v", err)
	}
	if ftsCount != memCount {
		t.Errorf("memories_fts rows = %d, memories rows = %d (row-preserving reindex)", ftsCount, memCount)
	}

	// Porter stemmer works: "cancellation" finds the row whose learned text
	// contains "cancel" (both stem to the same token).
	var title string
	if err := conn.QueryRow(`
		SELECT m.title FROM memories_fts fts
		JOIN memories m ON m.rowid = fts.rowid
		WHERE memories_fts MATCH 'cancellation'
		ORDER BY fts.rank LIMIT 1
	`).Scan(&title); err != nil {
		t.Errorf("porter stem MATCH 'cancellation': %v", err)
	} else if title != "cancel the sync job" {
		t.Errorf("porter MATCH returned %q, want the cancel row", title)
	}

	// A second Migrate is a no-op (version gate skips the rung).
	if err := db.Migrate(conn); err != nil {
		t.Errorf("second Migrate: %v", err)
	}
}

func TestInit_FreshDBHasOriginColumnAndIndex(t *testing.T) {
	conn := newTestDB(t)
	if !slices.Contains(tableColumns(t, conn, "memories"), "origin") {
		t.Error("fresh DB missing memories.origin")
	}
	if !slices.Contains(indexNames(t, conn), "idx_memories_origin_created") {
		t.Error("fresh DB missing idx_memories_origin_created")
	}
}

// v2→v3 adds origin; existing rows must backfill to 'manual' via the DEFAULT,
// and the recency index must exist after migrate.
func TestMigrate_V2toV3AddsOriginBackfillsManual(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	now := int64(1000000)
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
		VALUES ('mem_o', 'sess', 'crm', 'task_pattern', 't', 'w', 'l', '', 'fp_o', ?, ?)`,
		now, now); err != nil {
		t.Fatalf("seed row: %v", err)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if !slices.Contains(tableColumns(t, conn, "memories"), "origin") {
		t.Fatal("migrated DB missing memories.origin")
	}
	var origin string
	if err := conn.QueryRow(`SELECT origin FROM memories WHERE id = 'mem_o'`).Scan(&origin); err != nil {
		t.Fatalf("read origin: %v", err)
	}
	if origin != "manual" {
		t.Errorf("backfilled origin = %q, want 'manual'", origin)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
	if !slices.Contains(indexNames(t, conn), "idx_memories_origin_created") {
		t.Error("migrated DB missing idx_memories_origin_created")
	}
}

// A fresh DB carries the file-provenance relation.
func TestInit_FreshDBHasMemoryFilesTable(t *testing.T) {
	conn := newTestDB(t)
	if !tableExists(t, conn, "memory_files") {
		t.Error("fresh DB missing memory_files table")
	}
}

// v3→v4 adds memory_files without disturbing existing memories rows.
func TestMigrate_V3toV4AddsMemoryFiles(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	now := int64(1000000)
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
		VALUES ('mem_f', 'sess_f', 'crm', 'task_pattern', 't', 'w', 'l', '', 'fp_f', ?, ?)`,
		now, now); err != nil {
		t.Fatalf("seed row: %v", err)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if !tableExists(t, conn, "memory_files") {
		t.Fatal("migrated DB missing memory_files table")
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
	var id string
	if err := conn.QueryRow(`SELECT id FROM memories WHERE id = 'mem_f'`).Scan(&id); err != nil {
		t.Errorf("pre-existing row lost after migrate: %v", err)
	}
}

// The CHECK constraint must reject any origin outside {manual, auto} and accept
// 'auto' (the value an Auto-session-summary carries).
func TestOrigin_CheckConstraint(t *testing.T) {
	conn := newTestDB(t)
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at, origin)
		VALUES ('mem_bad', 'sess', 'crm', 'task_pattern', 't', 'w', 'l', '', 'fp_bad', 1, 1, 'bogus')`,
	); err == nil {
		t.Error("expected CHECK violation for origin='bogus', got nil")
	}
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at, origin)
		VALUES ('mem_auto', 'sess', 'claude_session', 'session_summary', 't', 'w', 'l', '', 'fp_auto', 1, 1, 'auto')`,
	); err != nil {
		t.Errorf("insert origin='auto' should succeed: %v", err)
	}
}

// hasLifecycleColumns reports whether cols contains the v6 lifecycle columns
// (ADR-0031: decay/review + pin).
func hasLifecycleColumns(cols []string) (hasReview, hasPinned bool) {
	for _, c := range cols {
		switch c {
		case "review_after":
			hasReview = true
		case "pinned":
			hasPinned = true
		}
	}
	return
}

func TestInit_FreshDBHasLifecycleColumns(t *testing.T) {
	conn := newTestDB(t)
	hasReview, hasPinned := hasLifecycleColumns(tableColumns(t, conn, "memories"))
	if !hasReview {
		t.Error("fresh DB missing memories.review_after")
	}
	if !hasPinned {
		t.Error("fresh DB missing memories.pinned")
	}
}

func TestInit_FreshDBHasArchivedMemoriesTable(t *testing.T) {
	conn := newTestDB(t)
	if !tableExists(t, conn, "archived_memories") {
		t.Error("fresh DB missing archived_memories table")
	}
}

// v5→v6 adds review_after (nullable) + pinned (default 0) without backfilling
// review_after on existing rows (D1 — grandfather NULL, never mass-flag
// legacy rows needs_review on day one).
func TestMigrate_V5toV6AddsLifecycleColumnsGrandfathersRows(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	now := int64(1000000)
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
		VALUES ('mem_lc', 'sess_lc', 'crm', 'task_pattern', 't', 'w', 'l', '', 'fp_lc', ?, ?)`,
		now, now); err != nil {
		t.Fatalf("seed row: %v", err)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	hasReview, hasPinned := hasLifecycleColumns(tableColumns(t, conn, "memories"))
	if !hasReview {
		t.Fatal("migrated DB missing memories.review_after")
	}
	if !hasPinned {
		t.Fatal("migrated DB missing memories.pinned")
	}

	var reviewAfter sql.NullInt64
	var pinned int
	if err := conn.QueryRow(`SELECT review_after, pinned FROM memories WHERE id = 'mem_lc'`).Scan(&reviewAfter, &pinned); err != nil {
		t.Fatalf("read migrated row: %v", err)
	}
	if reviewAfter.Valid {
		t.Errorf("migrated review_after = %v, want NULL (D1 — no backfill)", reviewAfter)
	}
	if pinned != 0 {
		t.Errorf("migrated pinned = %d, want 0", pinned)
	}
	if !tableExists(t, conn, "archived_memories") {
		t.Error("migrated DB missing archived_memories table")
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
}

// assertColumnParity is the D5/SM-R8 archived_memories drift guard: the table
// must carry exactly the memories column set plus archived_at. It is lazy-safe
// by design — no shared column-const in prod, just a test-time comparison — so
// a future ALTER on memories that forgets its archived_memories mirror fails
// loud here instead of silently dropping a column at archive time. The guard
// runs against fresh AND migrated databases (SM-R8).
func assertColumnParity(t *testing.T, conn *sql.DB) {
	t.Helper()
	memCols := tableColumns(t, conn, "memories")
	archCols := tableColumns(t, conn, "archived_memories")

	want := make(map[string]bool, len(memCols)+1)
	for _, c := range memCols {
		want[c] = true
	}
	want["archived_at"] = true

	got := make(map[string]bool, len(archCols))
	for _, c := range archCols {
		got[c] = true
	}

	for c := range want {
		if !got[c] {
			t.Errorf("archived_memories missing column %q (present in memories ∪ {archived_at})", c)
		}
	}
	for c := range got {
		if !want[c] {
			t.Errorf("archived_memories has extra column %q not in memories ∪ {archived_at}", c)
		}
	}
}

// v6→v7 widens the three recency-serving indexes to 4 columns (ADR-0033):
// task_type/kind, created_at, and origin composites all end in
// `created_at DESC, id DESC` so the newest-first tiebreak never needs a temp
// B-tree sort.
func TestMigrate_V6toV7RedefinesIndexes(t *testing.T) {
	conn := loadFixture(t, "schema_v0.sql")
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
	got := indexDefs(t, conn)
	want := []string{
		"idx_memories_created_at(created_at DESC,id DESC)",
		"idx_memories_fingerprint(fingerprint)",
		"idx_memories_kind(kind)",
		"idx_memories_origin_created(origin,created_at DESC,id DESC)",
		"idx_memories_task_kind_created(task_type,kind,created_at DESC,id DESC)",
		// No idx_memories_task_type: task_type is the composite's leftmost
		// column, so idx_memories_task_kind_created already serves every
		// task_type-only lookup and the v6→v7 rung drops the standalone index.
		// idx_memories_kind stays — kind is the composite's SECOND column, so
		// no leftmost prefix covers a kind-only lookup.
	}
	if !equalStringSlices(got, want) {
		t.Errorf("migrated index definitions = %v, want %v", got, want)
	}
}

// v7→v8 adds authored_at, backfilled to created_at so no pre-existing row
// misreports its authoring date as the epoch.
func TestMigrate_V7toV8AddsAuthoredAtBackfillsCreatedAt(t *testing.T) {
	conn := newPreV1DB(t)
	now := int64(1000000)
	if _, err := conn.Exec(`
		INSERT INTO memories (id, session_id, task_type, kind, title, what, learned, tags, fingerprint, created_at, updated_at)
		VALUES ('mem_au', 'sess_au', 'crm', 'task_pattern', 't', 'w', 'l', '', 'fp_au', ?, ?)`,
		now, now); err != nil {
		t.Fatalf("seed row: %v", err)
	}
	if err := db.Migrate(conn); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	if !slices.Contains(tableColumns(t, conn, "memories"), "authored_at") {
		t.Fatal("migrated DB missing memories.authored_at")
	}
	if !slices.Contains(tableColumns(t, conn, "archived_memories"), "authored_at") {
		t.Fatal("migrated DB missing archived_memories.authored_at")
	}
	var authoredAt int64
	if err := conn.QueryRow(`SELECT authored_at FROM memories WHERE id = 'mem_au'`).Scan(&authoredAt); err != nil {
		t.Fatalf("read authored_at: %v", err)
	}
	if authoredAt != now {
		t.Errorf("backfilled authored_at = %d, want created_at %d", authoredAt, now)
	}
	if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
		t.Errorf("post-migrate user_version = %d, want %d", got, want)
	}
}

// A fresh DB carries authored_at from schema.go directly and reports the
// current head version.
func TestInit_FreshDBHasAuthoredAtAndVersion8(t *testing.T) {
	conn := newTestDB(t)
	if !slices.Contains(tableColumns(t, conn, "memories"), "authored_at") {
		t.Error("fresh DB missing memories.authored_at")
	}
	if !slices.Contains(tableColumns(t, conn, "archived_memories"), "authored_at") {
		t.Error("fresh DB missing archived_memories.authored_at")
	}
	if got, want := userVersion(t, conn), 8; got != want {
		t.Errorf("fresh DB user_version = %d, want %d", got, want)
	}
}

func equalStringSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func TestArchivedMemories_ColumnParityWithMemories(t *testing.T) {
	t.Run("fresh", func(t *testing.T) {
		assertColumnParity(t, newTestDB(t))
	})
	// SM-R8: the guard must also hold on the migrated path — the v5 fixture
	// predates the rung that creates archived_memories, so this exercises the
	// rung-created table, not just the fresh DDL.
	t.Run("v5-migrated", func(t *testing.T) {
		conn := loadFixture(t, "schema_v5.sql")
		if tableExists(t, conn, "archived_memories") {
			t.Fatalf("v5 fixture has archived_memories — wrong fixture shape (rung 5→6 creates it)")
		}
		if err := db.Migrate(conn); err != nil {
			t.Fatalf("Migrate: %v", err)
		}
		if got, want := userVersion(t, conn), db.CurrentSchemaVersion; got != want {
			t.Errorf("post-migrate user_version = %d, want %d", got, want)
		}
		assertColumnParity(t, conn)
	})
}
